services:
  mongodb:
    image: mongo:5.0
    container_name: personal_finance_tracker_mongodb
    ports:
      - "27200:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: Finance-Tracker
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    command: mongod --bind_ip_all
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G